export const ORDER_STATUS = {
  PENDING: 'PENDING',
  PRESCRIPTION_REVIEW: 'PRESCRIPTION_REVIEW',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  READY: 'READY',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;

export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];

export const APPOINTMENT_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  RESCHEDULED: 'RESCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type AppointmentStatus = (typeof APPOINTMENT_STATUS)[keyof typeof APPOINTMENT_STATUS];

export const PRESCRIPTION_STATUS = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
} as const;

export type PrescriptionStatus = (typeof PRESCRIPTION_STATUS)[keyof typeof PRESCRIPTION_STATUS];

export const HEALTH_RECORD_CATEGORIES = {
  PRESCRIPTIONS: 'PRESCRIPTIONS',
  LAB_REPORTS: 'LAB_REPORTS',
  MEDICAL_DOCUMENTS: 'MEDICAL_DOCUMENTS',
  DOCTOR_VISITS: 'DOCTOR_VISITS',
} as const;

export type HealthRecordCategory = (typeof HEALTH_RECORD_CATEGORIES)[keyof typeof HEALTH_RECORD_CATEGORIES];
